---
## tasks file for dnsmasq
- name: install dnsmasq
  apt:
          name: dnsmasq
          state: present
  tags: [install]
                
- name: config dnsmasq
  copy:
          content: "{{item.content}}"
          dest: "/etc/dnsmasq.d/{{item.prio | default('10') }}-{{item.name}}.conf"
  with_items: "{{dnsmasq_config}}"
  notify:
          - dnsmasq restart
  tags: [config]
