---
- name: Systemd_resolved | Checking If systemd-resolved Service Is Present
  ansible.builtin.command: systemctl status systemd-resolved.service
  register: _dnsmasq_systemd_resolved_check
  become: true
  changed_when: false
  failed_when: false

- name: Systemd_resolved | Disabling and Stopping systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true
  register: _dnsmasq_systemd_resolved_disabled
  notify: "dnsmasq restart"
  when: _dnsmasq_systemd_resolved_check['rc'] == 0

- name: Systemd_resolved | Checking If /etc/resolv.conf Exists
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: _dnsmasq_resolv_conf

- name: Systemd_resolved | Removing Existing /etc/resolv.conf If symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true
  tags:
    - skip_ansible_lint
  register: _dnsmasq_resolv_conf_removed
  when:
    - _dnsmasq_systemd_resolved_disabled['changed']
    - _dnsmasq_resolv_conf['stat']['islnk']

- name: Systemd_resolved | Creating /etc/resolv.conf
  ansible.builtin.copy:
    content: |
      nameserver 127.0.0.1
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: o=rw,g=r,o=r
  become: true
  notify: "dnsmasq restart"
  tags:
    - skip_ansible_lint
  when:
    - _dnsmasq_resolv_conf_removed['changed']
